### ISSUE TITLE
add accordingTo as a parameter to search for interactions

### ISSUE THREAD

**Issue by jhpoelen** [ropensci/rglobi#16]
@dupontcai @tmitchell1 @jsimons9 were interested to calculate the number of unique predator taxa reported by gomexsi (a data source) using rglobi. Currently, this can be done by using a custom cypher query like:

```R
rglobi::query('START study = node:studies("*:*") WHERE study.source =~ ".*gomexsi.*" WITH study MATCH study-[:COLLECTED]-predator-[:ATE|PREYS_ON]->prey, predator-[:CLASSIFIED_AS]->predatorTaxon RETURN count(distinct(predatorTaxon.name))')
```

Rather than having to run this custom query, I'd like to suggest to add a parameter like ```accordingTo``` to the existing (highlevel) rglobi methods, so that you can do stuff like:

```R
rglobi::get_interactions(accordingto = 'gomexsi')
```
or perhaps
```R
rglobi::get_predators(accordingto = 'gomexsi')
```

This would retrieve all (distinct) interactions reported by gomexsi. This functionality is already used in the GloBI API, but has not yet been implemented in rglobi. For example see [here](http://www.globalbioticinteractions.org/#sourceTaxon=Scomberomorus%20cavalla&interactionType=eats&accordingTo=gomexsi) .

**Comment by jemmybutton** [comment]
Here's `accordingto` parameter added to `get_interactions_by_taxa` parameters:
[https://github.com/jemmybutton/rglobi/commit/8f6aa6391a070e88f95a0df116c60b340bf83754](https://github.com/jemmybutton/rglobi/commit/8f6aa6391a070e88f95a0df116c60b340bf83754)
It seems to work, but data source is not listed in output (?), so i can't really test it. And i'm not sure if this parameter should be passed to all this `get_predator` and `get_prey_of` stuff.

**Comment by jhpoelen** [comment]
@jemmybutton Thanks for adding this!

About the source output - in the api, you can now specify the fields that you'd like to see [docs](https://github.com/jhpoelen/eol-globi-data/wiki/API#selecting-return-fields), rglobi isn't really using that yet. Do you think we should support this in some way in rglobi?

About using the accordingto in other function - it almost sounds like we need some way way to specify the (search) context in which a specific interaction search is made. Some folks are interested in searching by location, taxon, interaction or, in this case, by source / study. I've seen other packages use stuff like: 

```R
result <- some_function(main_argument = 'bla', opts = list(location=123, source='somesource' )
```
now, the ```opts``` can be easily passed around without having to have a huge list of function arguments.

Curious to hear your thoughts on this.

**Comment by jsimons9** [comment]
Thanks Jorrit,

  So it looks like it should be relatively easy (for some) to add a little code to your script to not only do the count, but provide the list of 349 predators, no??

Jim

**Comment by jhpoelen** [comment]
@jsimons9 yep - rglobi and Cypher is a powerful combination once you get familiar using the tools.

**Comment by jemmybutton** [comment]
@jhpoelen 
Fields can be handled just the same way: [https://github.com/jemmybutton/rglobi/commit/c9cf22af1b223ea8be681c8ba9ca8ddfc361d906](https://github.com/jemmybutton/rglobi/commit/c9cf22af1b223ea8be681c8ba9ca8ddfc361d906)
But i can't figure out which one of [available fields](http://api.globalbioticinteractions.org/interactionFields) contains a requested provider (i. e. `gomexsi` for the example above)
Using a list of arguments seems logical, but since functions like `get_predators_of` essentially do nothing but call `get_interactions_by_taxa` it will make them virtually identical (why not get parasites with function for predators then, for example?), which might not be a bad thing, but maybe it would be better not to encourage usage of these frontends in more complex contexts and suggest using  `get_interactions_by_taxa` directly instead?

**Comment by jhpoelen** [comment]
I am ok with removing the get_predator_of and get_prey_of functions, as long as we have sensible defaults for the other methods. The idea was that adding these methods would make it easy to get started using the library.

I wasn't quite clear on which fields are used to when using the accordingTo . I've just added some documentation here: https://github.com/jhpoelen/eol-globi-data/wiki/API#selecting-specific-studies-or-sources . Let me know if that explains it. If not, I'd be happy to add more info. There is a property in the [available fields](http://api.globalbioticinteractions.org/interactionFields) for describing individual fields. Do you think it would help to add some text to that explaining the relationship also?

**Comment by jhpoelen** [comment]
@jsimons9 @dupontcai - I've updated the example in https://github.com/GoMexSI/workshop/wiki/R-scripts#food-of-king-mackerel-scomberomorus-cavalla to reflect the changes that @jemmybutton made. Please note that you'll have to install a new version of rglobi using devtools if you'd like to use this new functionality until version 0.2.7 is released.

Big thanks to @jemmybutton for introducing to accordingto parameter in rglobi!
