### ISSUE TITLE
New to rglobi/cypher - error message not understood

### ISSUE THREAD

**Issue by jsimons9** [ropensci/rglobi#19]
I am trying to get a list of the studies that are currently in the gomexsi database using the below code, but keep getting the error message noted below the code. Not really sure of the problem. Similar code had the same ":" in it and worked.

> rglobi::query('START study = node:studies('*:*') WHERE study.source =~ ".*gomexsi.*" WITH study  RETURN distinct(study)')

Error: unexpected ':' in "rglobi::query('START study = node:studies('*:"

Thanks for any help.

**Comment by jhpoelen** [comment]
@jsimons9 great start!

Some things that might help:
1. use quotes consistently: either use a single quote to delimit R strings (see example below), and double quotes to delimit strings in cypher (e.g. ```... study.source =~ ".*gomexsi.*") or the other way around.
1. make sure to include the ```*``` wildcards. (e.g. ```node:studies(":")```` should be ```node:studies("*:*")``` and ```study.source =~ ".gomexsi."``` should be ```study.source =~ ".*gomexsi.*")
1. separate the cypher query from the rglobi::query function call using a variable:
```R
# first define the query
studyQuery <- 'START study = node:studies("*:*") WHERE study.source =~ ".*gomexsi.*" WITH study RETURN distinct (study.citation)'
# then execute the query and assign the result to a variable
queryResult <- rglobi::query(studyQuery)
# show the variable
queryResult
```

Close close this issue when you questions is addressed.

**Comment by jsimons9** [comment]
OK, thanks, that worked.  I thought that those wildcards were in the original - the copy looked a little weird.
