### ISSUE TITLE
NEWS and releases

### ISSUE THREAD

**Issue by sckott** [ropensci/rglobi#21]
hi @jhpoelen  - would you mind using a `NEWS` file, and tag each CRAN release, and write a release with relevant `NEWS` section for that tag in github Releases https://github.com/ropensci/rglobi/releases ?   And link to issues in the releases if you can. e.g., (https://github.com/ropensci/rgbif/releases/tag/v0.8.4)

would be easier to see what's been changed in each version :)

**Comment by jhpoelen** [comment]
hey @sckott - I've added a NEWS files and added the changes for latest release (see https://github.com/ropensci/rglobi/releases/tag/v0.2.8). Going forward, I'll make an effort to provide release info. Please close this issue if this addresses your suggestion. Thanks!

**Comment by sckott** [comment]
yeah, looks good !
