### ISSUE TITLE
Provide example of specimen volume field

### ISSUE THREAD

**Issue by camainsworth** [ropensci/rglobi#22]
I'd like an example of how to use rglobi that will return volume of prey within a defined lat/long coordinate range within a predator family.

Ideally the output should be an array with predator species in column 1, predator stomach ID# in column 2, prey species in column 3 and prey volume in column 4.  There may be several rows from any particular predator stomach, with each row representing a prey item found within that stomach.  The table would therefore contain every prey item in every stomach of every predator sampled from within that family, where samples originated within the specified coordinate range.

**Comment by jhpoelen** [comment]
Hi @camainsworth ! 

The example below hopefully provides what you need. Note that the fields ```tmp_and_unique_source_specimen_id``` is a temporary (internal) id assigned to each source specimen ( in this case the stomach of a predator).

```R
mackerelPreyItems <- rglobi::get_interactions_by_taxa(sourcetaxon=c('Scomberomorus cavalla'), showfield = c('source_taxon_name', 'target_taxon_name', 'tmp_and_unique_source_specimen_id', 'target_specimen_total_volume_ml', 'latitude','longitude'), returnobservations=T) 

names(mackerelPreyItems)
#[1] "source_taxon_name"                 "target_taxon_name"                
#[3] "tmp_and_unique_source_specimen_id" "target_specimen_total_volume_ml"  
#[5] "latitude" 

# show the dimensions (number of rows, number of columns)
dim(mackerelPreyItems)
# [1] 1024    6

# show first bunch of records without any NAs 
head(na.omit(mackerelPreyItems))
#        source_taxon_name    target_taxon_name
#353 Scomberomorus cavalla             Detritus
#354 Scomberomorus cavalla Decapterus punctatus
#355 Scomberomorus cavalla       Actinopterygii
#356 Scomberomorus cavalla       Actinopterygii
#362 Scomberomorus cavalla             Detritus
#363 Scomberomorus cavalla       Actinopterygii
#    tmp_and_unique_source_specimen_id target_specimen_total_volume_ml latitude
#353                           1401377                          0.0077 26.92442
#354                           1401371                         48.0000 26.92442
#355                           1401371                          0.2011 26.92442
#356                           1401367                          0.1131 26.92442
#362                           1401342                          0.4000 26.92442
#363                           1401342                         59.0000 26.92442
 #   longitude
#353 -82.60468
#354 -82.60468
#355 -82.60468
#356 -82.60468
#362 -82.60468
#363 -82.60468
#> 
```

Note that only the first 1024 records are shown by default. If you'd like to retrieve all results, either increase the limit, or (recommended) page through all the result. 

Example of getting 32 results after skipping 512 records:
```R
catfishPredatorNames <- rglobi::get_interactions_by_taxa(sourcetaxon=c('Scomberomorus'), showfield = c('source_taxon_name', 'target_taxon_name', 'tmp_and_unique_source_specimen_id', 'target_specimen_total_volume_ml', 'latitude','longitude'), returnobservations=T, otherkeys=list(limit=32, skip=512))
```

Please close this issue if this answered your question. Otherwise, please clarify.

**Comment by camainsworth** [comment]
Wonderful, thank you Jorrit.  Let me play around with this.
