### ISSUE TITLE
keep github releases up to date with CRAN releases

### ISSUE THREAD

**Issue by sckott** [ropensci/rglobi#24]
hey @jhpoelen    - We want all rOpenSci pkgs to consistently keep track of changes, following https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#-news  

* you already keep a `NEWS` file, thanks!
* thanks for git tagging!
* You have used the [releases tab](https://github.com/ropensci/rglobi/releases) on this repo to include the associated NEWS items for each tag/version - thanks for that, but can you make sure to git tag each release, and put the NEWS items in each release in the releases tab? e.g., right now CRAN is at version 0.2.9, while most recent release is at 0.2.8 -  thanks! 😄

**Comment by jhpoelen** [comment]
@sckott thanks for letting me know. I've created https://github.com/ropensci/rglobi/releases/tag/v0.2.9 . Please close this issue if this addresses your comments.

**Comment by sckott** [comment]
Great, thanks! and if you could do so moving forward as well

thanks!
