### ISSUE TITLE
Amount of data accessible with this pkg?

### ISSUE THREAD

**Issue by sckott** [ropensci/rglobi#34]
👋  as part of preparing an rOpenSci annual report, we're trying to estimate amount of data the various pkgs in our suite provide access to.

Do you have a sense for how much data (e.g., in GB) one can access through this pkg?  And/or whatever metric is most relevant for this data (datasets maybe?)?

**Comment by jhpoelen** [comment]
@sckott thanks for asking

from https://www.globalbioticinteractions.org/references.html today -

"467,632 references obtained [...] 3,716,139 interaction records were discovered, covering 248,246 taxa"

Data volume downloading all data from GloBI through rglobi can be estimated by looking at sizes of data products at https://www.globalbioticinteractions.org/data ~ 320MB gz compressed so > GB uncompressed.

To be honest, I am a bit of a metric skeptic - especially considering the long tail of science and my perceived concentration of grant funds in relatively few influential and well-marketed projects. 

Is bigger better?

**Comment by sckott** [comment]
Okay, thanks very much!
