### ISSUE TITLE
Add vignette titles

### ISSUE THREAD

**Issue by jeroen** [ropensci/rglobi#35]
Give titles to vignettes: https://docs.ropensci.org/rglobi/articles/

**Comment by jhpoelen** [comment]
Thanks! I've added some front-matter to vignette .Rmd
 via https://github.com/ropensci/rglobi/commit/3858c53c13e80fa444305b39e83e1c9096de8e43 . Please let me know if this addresses your concern. 

groetjes,
-jorrit

**Comment by jhpoelen** [comment]
Assuming concern has been addressed. Thanks @jeroen for sharing your improvement ideas.
