### ISSUE TITLE
list dataframe from start query

### ISSUE THREAD

**Issue by bonushenricus** [ropensci/rglobi#39]
Greetings
I'm studying Cypher to use in Rglobi
I don't understand how to get START to take a list of species (from a data.frame)
For example this list
`c('Ablaxia parviclara','Ablaxia squamifera','Ablerus celsus')`
Thank you

**Comment by jhpoelen** [comment]
@bonushenricus thanks for your question. 

Before jumping into the details, could you please share what kind of data you are looking for? If I know more about this, I might be able to point to some alternative ways to get to the data as Cypher can be a bit overly complex sometimes.

**Comment by bonushenricus** [comment]
Hello Jorrit and thank you
I wanted to check if with a string in Cypher I can see if there are any hyperparasitoids.
In R I made a string with pastes from the dataframe
paste0 ("path:", masini_bosco $ `valid name`, collapse =" ")
or
paste0 ("name = '", masini_bosco $ `valid name`, collapse ="' ")
the result is attached
they are all Chalcidoidea
among them they are sometimes hyperparasitoids
but i don't understand how to take my string and put it inside the query
[prova.txt](https://github.com/ropensci/rglobi/files/7157087/prova.txt)

**Comment by jhpoelen** [comment]
Thanks for sharing. Can you please include the R code that you are using, including the Cypher snippet ?

**Comment by bonushenricus** [comment]
Hello.
with only two species for try
`query("START sourceTaxon = node:taxons(name='Anagrus atomus' name='Ablaxia parviclara'),targetTaxon = node:taxons(name='Anagrus atomus' name='Ablaxia parviclara') MATCH sourceTaxon<-[:CLASSIFIED_AS]-source-[rel:EATEN_BY|HAS_PARASITE]->target-[:CLASSIFIED_AS]->targetTaxon RETURN distinct(targetTaxon.name),type(rel),sourceTaxon.name")`
but I believe a "where" clause is necessary, but where.
Excuse-me, I read a little https://neo4j.com/docs/cypher-manual/current/ but I didn't understand everything

**Comment by jhpoelen** [comment]
If you are looking for hyper parasites, one way to find them is to:

```
START 
sourceTaxon = node:taxons("name:\"Anagrus atomus\" name:\"Ablaxia parviclara\"") 
MATCH 
sourceTaxon<-[:CLASSIFIED_AS]-source-[rel]->target-[:CLASSIFIED_AS]->targetTaxon, targetTaxon<-[:CLASSIFIED_AS]-otherSource-[otherRel:PARASITE_OF]->otherTarget-[:CLASSIFIED_AS]->otherTargetTaxon 

RETURN 
distinct(targetTaxon.name),type(rel),sourceTaxon.name, type(otherRel), otherTargetTaxon.name
```


Alternatively, using the path index:

```

To include multiple names, you can do something like:

```
START 
sourceTaxon = node:taxons("name:\"Anagrus atomus\"") 
MATCH 
sourceTaxon<-[:CLASSIFIED_AS]-source-[rel]->target-[:CLASSIFIED_AS]->targetTaxon, targetTaxon<-[:CLASSIFIED_AS]-otherSource-[otherRel:PARASITE_OF]->otherTarget-[:CLASSIFIED_AS]->otherTargetTaxon 
RETURN 
distinct(targetTaxon.name),type(rel),sourceTaxon.name, type(otherRel), otherTargetTaxon.name
```

Similarly, you can use the taxon paths index like to select taxa with "Anagrus" or "Ablaxia" in their paths

```
START 
sourceTaxon = node:taxonPaths("path:Anagrus path:Ablaxia") 
MATCH 
sourceTaxon<-[:CLASSIFIED_AS]-source-[rel]->target-[:CLASSIFIED_AS]->targetTaxon, targetTaxon<-[:CLASSIFIED_AS]-otherSource-[otherRel:PARASITE_OF]->otherTarget-[:CLASSIFIED_AS]->otherTargetTaxon 

RETURN 
distinct(targetTaxon.name),type(rel),sourceTaxon.name, type(otherRel), otherTargetTaxon.name

```

**Comment by jhpoelen** [comment]
Please do note that you may have to change the Cypher queries sooner rather than later, because of a pending upgrade from neo4j 2.3.12 to 3.4.18 . In this version, the "start ..." clause is replaced with more elegant ways to do queries. However, I expected the basic structure of the query will remain the same.

**Comment by jhpoelen** [comment]
By the way, I assume that R scripts that rely on online resources will no longer work. For research, I prefer to use identical copies of versioned datasets, so that I don't have to worry about some server going down (i.e. link rot) or web content changing over time (i.e. content drift). That said, online queries can be quite useful when doing exploratory analysis.

**Comment by bonushenricus** [comment]
Thank you very much for your availability.
On Saturday there is a demonstration of entomologists in Modena, the city near which I live, and I participate and I would have liked to discuss these possibilities, but first I had to try. That's why I was in a bit of a hurry.
A question: inside the query I can't put the reference to other packages and dataframes in R, I think, or maybe there is the possibility? That is, the string with paste0 cannot be inserted into the query, instead of copying and pasting everything.
I will also download the data.
Thanks again

**Comment by jhpoelen** [comment]
@bonushenricus thanks for your message and how exciting that you are doing a demonstration for entomologist in Modena on Saturday. Can you please elaborate on what it is your are trying to achieve? Perhaps some pseudo-code (or step-by-step narrative) would help me to understand what specific question you'd like to answer, and how you'd like to reference packages and dataframes in R.

**Comment by bonushenricus** [comment]
Hi Jorrit
I understood
you can use a dataframe in the various functions of the module without using the query
for example with get_interaction_table
with an example code
get_interaction_table (source.taxon.names = list (paste0 ("'", phytophagous horticulture $ valid_name, "'", collapse = ""))), target.taxon.names = list (paste0 ("'", chalcidoidea $ `valid name `," '", collapse =" ")))
in which phytofagi_horticulture and chalcidoidea are two dataframes with a list of names.
Now there are some things to understand:
- the form of the list in get_interactions (because the quotes give me some problems)
- how to work offline (I saw that there are some open issues)

**Comment by jhpoelen** [comment]
@bonushenricus Please note that the GloBI How To page might have some ideas to access species interactions data. On this page, you'll also find recorded workshops with exercises. If this doesn't answer your questions, please feel free to comment or open a new issue.

Thanks for being patient.
