### ISSUE TITLE
push early version to CRAN.

### ISSUE THREAD

**Issue by jhpoelen** [ropensci/rglobi#4]

**Comment by jhpoelen** [comment]
@sckott @jemmybutton @jsgosnell Before attempting to push a version of rglobi to CRAN, I wanted to ask you all: what do you think we should improve / change before releasing rglobi to CRAN?

**Comment by sckott** [comment]
hi @jhpoelen - a few things:

- I'm submitting a pull request with some minor changes to the vignette. here: https://github.com/ropensci/rglobi/pull/15
- DESCRIPTION file: 
    - They will want the `Title` in sentence case, like _Hello World_, with no period at the end (ripley will get angry if it's not this way)
    - Put a little bit more in the `Description` field about the package as they often ask for more details on the package in that field
- Running check returns a few things:
    - `Found the following hidden files and directories:  inst/.gitkeep`
    - No packages are imported, but are listed in DESCRIPTION file and seem to be used in the package, these should have one instance of `@import httr RCurl` or `@importFrom ...` to import particular functions. 
     - Some lines in man files are longer than 100 characters, should be shorter
     - There's a number of parameters that aren't documented, and some that are documented but not in use, and some duplicated param definitions
    - You can leave examples to run on R CMD CHECK, but since at least I assume all work with a web API, you may want to consider wrapping on `\dontrun` since if they fail on CRAN they may archive the package
- Would be nice if data.frame's returned didn't have strings converted to factors, e.g., 

```r
str( get_interactions_by_taxa(sourcetaxon = "Rattus") )

'data.frame':	395 obs. of  12 variables:
 $ source_taxon_external_id  : Factor w/ 17 levels "EOL:1179360",..: 13 13 13 13 13 13 13 13 13 13 ...
 $ source_taxon_name         : Factor w/ 17 levels "Rattus","Rattus argentiventer",..: 12 12 12 12 12 12 12 12 12 12 ...
 $ source_taxon_path         : Factor w/ 17 levels "Animalia | Bilateria | Deuterostomia | Chordata | Vertebrata | Gnathostomata | Tetrapoda | Mammalia | Theria | Eutheria | Roden"| __truncated__,..: 2 2 2 2 2 2 2 2 2 2 ...
 $ source_specimen_life_stage: logi  NA NA NA NA NA NA ...
 $ interaction_type          : Factor w/ 5 levels "ATE","EATEN_BY",..: 5 5 5 5 5 5 5 5 5 5 ...
 $ target_taxon_external_id  : Factor w/ 234 levels "AFD:01b45e80-98b3-475d-86c2-06f54734eb8d",..: 101 75 166 164 160 156 155 122 121 98 ...
 $ target_taxon_name         : Factor w/ 239 levels "Acanthopsylla pavida",..: 133 231 47 187 144 217 228 220 123 114 ...
 $ target_taxon_path         : Factor w/ 233 levels "","Allanblackia stuhlmannii",..: 173 191 184 177 175 170 204 224 197 195 ...
 $ target_specimen_life_stage: logi  NA NA NA NA NA NA ...
 $ latitude                  : logi  NA NA NA NA NA NA ...
 $ longitude                 : logi  NA NA NA NA NA NA ...
 $ study_title               : logi  NA NA NA NA NA NA ...
```

**Comment by jemmybutton** [comment]
It's not very good that interaction types referenced in API call are different from ones that are in its output. (i mean `get_interactions_by_taxa(sourcetaxon = "Felis", interactiontype = "hostOf")$interaction_type[1]` returns `"HAS_PARASITE"` not `"hostOf"`). There's of course `rel_type_interaction_type` function, but it doesn't handle all interaction types and types are written by hand, so changes on the server side in this respect will break it anyway. 
I think, resolving this things are important for the library to be usable (or i'm missing something?).

**Comment by jhpoelen** [comment]
@sckott @jemmybutton thanks for providing your feedback.

I've attempted to incorporate your suggestions:

1. cleaned up DESCRIPTION, NAMESPACE files
2. dontrun for examples
3. names are now interpreted as strings rather than factors
4. interaction types returned by functions are now consistent with the ```get_interaction_types```:

```R
> cat_bugs <- rglobi::get_interactions_by_taxa(sourcetaxon = "Felis", interactiontype = c("hasParasite"))
> unique(cat_bugs$interaction_type)
[1] "hasParasite"
```
This and other changes reduced the```devtools::check()``` to produce no more notes/ warnings /errors.

Also, I've added @jemmybutton to the author list in DESCRIPTION file. Could you please confirm that the information is desired / accurate.

Should we address any more issue before publishing the package?

**Comment by jhpoelen** [comment]
PS the interaction type ```hasHost``` has been replaced with ```hasParasite```. The idea is that the interaction is a little less ambiguous than before.

**Comment by sckott** [comment]
i can't think of anything else

**Comment by jhpoelen** [comment]
@sckott thanks again for your help. If you'd like authorship of this package, please add your name in a pull request.

@jemmybutton @jsgosnell please let me know if you have any suggestions. I am planning to submit by tomorrow if no other issues arise.

**Comment by sckott** [comment]
@jhpoelen thanks very much for the offer! i won't now, if I contribute more to the code base in the future i may ask

**Comment by jemmybutton** [comment]
@jhpoelen yes, everything seems correct, thank you. Neither i see any critical issues at the moment

**Comment by jhpoelen** [comment]
@sckott @jemmybutton @jsgosnell rglobi is now available on [CRAN](http://cran.r-project.org/web/packages/rglobi/index.html). I am hoping that this increased visibility will help us (and other future contributors) to make the package better.

**Comment by sckott** [comment]
great! :+1:

**Comment by jemmybutton** [comment]
great news!
