### ISSUE TITLE
data frame with 0 columns and 0 rows

### ISSUE THREAD

**Issue by mabarbour** [ropensci/rglobi#40]
I don't understand why this is happening, but the following code snippet from the beginning of the rglobi vignette reports `data frame with 0 columns and 0 rows`:

`library("rglobi")
hsapiens <- get_interactions(taxon = "Homo sapiens", interaction.type = "preysOn")
head(hsapiens)`

Any idea why this could be happening?

Here is the output of `sessionInfo()`:

R version 4.1.1 (2021-08-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.7 LTS

Matrix products: default
BLAS:   /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] rglobi_0.2.25

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13  magrittr_2.0.1   hms_1.1.0       
 [4] tidyselect_1.1.1 bit_4.0.4        R6_2.5.1        
 [7] rlang_0.4.11     fansi_0.5.0      tools_4.1.1     
[10] parallel_4.1.1   vroom_1.5.4      utf8_1.2.2      
[13] cli_3.0.1        withr_2.4.2      ellipsis_0.3.2  
[16] bit64_4.0.5      tibble_3.1.3     lifecycle_1.0.0 
[19] crayon_1.4.1     purrr_0.3.4      readr_2.0.1     
[22] tzdb_0.1.2       vctrs_0.3.8      bitops_1.0-7    
[25] RCurl_1.98-1.3   curl_4.3.2       glue_1.4.2      
[28] compiler_4.1.1   pillar_1.6.2     pkgconfig_2.0.3

**Comment by jhpoelen** [comment]
Hi @mabarbour - thanks for taking the time to report this issue. I've reproduced your issue and traced it back to a silly problem: a hard disk out of space issue. This is a bit of a luxury problem as GloBI has been growing substantially lately . . . sorry for the inconvenience.

I am working to resolve the problem as we speak.

**Comment by jhpoelen** [comment]
After re-instantiating the search index, I was able to run:

```
> head(rglobi::get_interactions(taxon = "Homo sapiens", interaction.type = "preysOn"))
  source_taxon_external_id source_taxon_name                                  
1               EOL:327955      Homo sapiens
2               EOL:327955      Homo sapiens
3               EOL:327955      Homo sapiens
4               EOL:327955      Homo sapiens
5               EOL:327955      Homo sapiens
6               EOL:327955      Homo sapiens
                                                            source_taxon_path
1 Animalia | Chordata | Mammalia | Primates | Hominidae | Homo | Homo sapiens
2 Animalia | Chordata | Mammalia | Primates | Hominidae | Homo | Homo sapiens
3 Animalia | Chordata | Mammalia | Primates | Hominidae | Homo | Homo sapiens
4 Animalia | Chordata | Mammalia | Primates | Hominidae | Homo | Homo sapiens
5 Animalia | Chordata | Mammalia | Primates | Hominidae | Homo | Homo sapiens
6 Animalia | Chordata | Mammalia | Primates | Hominidae | Homo | Homo sapiens
  source_specimen_life_stage interaction_type target_taxon_external_id
1                         NA          preysOn                 no:match
2                         NA          preysOn                 no:match
3                         NA          preysOn                 no:match
4                         NA          preysOn                 no:match
5                         NA          preysOn                 no:match
6                         NA          preysOn             GBIF:2434812
   target_taxon_name
1   demersal species
2      coconut crabs
3    fish carnivores
4    fish herbivores
5 prawns and shrimps
6           Mirounga
```

Please confirm that the issue has been resolved by closing this issue.

Thanks for being patient.

**Comment by mabarbour** [comment]
Thanks! I can confirm that this has resolved the issue.
