### ISSUE TITLE
too many taxa result in "Error in open.connection(5L, "rb") : HTTP error 414."

### ISSUE THREAD

**Issue by amynang** [ropensci/rglobi#41]
Hello, trying to retrieve the interaction matrix for a large number of species, I get the error quoted in the title.

This should reproduce the error:

`library(tidyverse)
library(rglobi)

temp1 <- tempfile()
download.file("https://esajournals.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2Fecy.2679&file=ecy2679-sup-0001-Supinfo.zip",temp1)
data <- read.csv(unzip(unzip(temp1)[1])[1])
taxa = data$genus.species
taxa = taxa %>% str_replace("_", " ")
taxa = taxa[10:714] 
mat = get_interaction_matrix(taxa,taxa,"eats")`

As a workaround, I broke the species list to 4 subsets that would then need to be combined:
(running all of them would take some time)

`mat.1 = get_interaction_matrix(taxa[1:177], 
                               taxa[1:177],"eats")
mat.5 = get_interaction_matrix(taxa[1:177], 
                               taxa[178:354],"eats")
mat.6 = get_interaction_matrix(taxa[1:177], 
                               taxa[355:531],"eats")
mat.7 = get_interaction_matrix(taxa[1:177], 
                               taxa[532:705],"eats")

mat.2 = get_interaction_matrix(taxa[178:354], 
                               taxa[178:354],"eats")
mat.8 = get_interaction_matrix(taxa[178:354], 
                               taxa[1:177],"eats")
mat.9 = get_interaction_matrix(taxa[178:354], 
                               taxa[355:531],"eats")
mat.10 = get_interaction_matrix(taxa[178:354], 
                               taxa[532:705],"eats")

mat.3 = get_interaction_matrix(taxa[355:531], 
                               taxa[355:531],"eats")
mat.11 = get_interaction_matrix(taxa[355:531], 
                               taxa[1:177],"eats")
mat.12 = get_interaction_matrix(taxa[355:531], 
                               taxa[178:354],"eats")
mat.13 = get_interaction_matrix(taxa[355:531], 
                               taxa[532:705],"eats")

mat.4 = get_interaction_matrix(taxa[532:705], 
                               taxa[532:705],"eats")
mat.14 = get_interaction_matrix(taxa[532:705], 
                               taxa[1:177],"eats")
mat.15 = get_interaction_matrix(taxa[532:705], 
                               taxa[178:354],"eats")
mat.16 = get_interaction_matrix(taxa[532:705], 
                               taxa[355:531],"eats")`

This works, with an occasional inscrutable warning

> Warning message:
In browseURL(paste0("http://127.0.0.1:", port, "/library/", pkgname,  :
  closing unused connection 3 (https://api.globalbioticinteractions.org:443/interaction?&sourceTaxon=Daucus%20carota&targetTaxon=Daucus%20carota&targetTaxon=Heracleum%20sphondylium&targetTaxon=Pastinaca%20sativa&targetTaxon=Pimpinella%20major&targetTaxon=Achillea%20millefolium&targetTaxon=Bellis%20perennis&targetTaxon=Centaurea%20jacea&targetTaxon=Cirsium%20oleraceum&targetTaxon=Crepis%20biennis&targetTaxon=Leontodon%20autumnalis&targetTaxon=Leontodon%20hispidus&targetTaxon=Leucanthemum%20vulgare&targetTaxon=Taraxacum%20officinale&targetTaxon=Tragopogon%20pratensis&targetTaxon=Campanula%20patula&targetTaxon=Cardamine%20pratensis&targetTaxon=Rumex%20acetosa&targetTaxon=Knautia%20arvensis&targetTaxon=Primula%20veris&targetTaxon=Lathyrus%20pratensis&targetTaxon=Lotus%20corniculatus&targetTaxon=Medicago%20lupulina&targetTaxon=Medicago%20x&targetTaxon=Onobrychis%20viciifolia&targetTaxon=Trifolium%20campestre&targetTaxon=Trifolium%20dubium&targetTaxon=Trifolium%20fragiferum&targetTaxon=Trifoli [... truncated]

Is there a way to avoid this?

Thanks,
Angelos

**Comment by jhpoelen** [comment]
@amynang am closing this issue because you didn't respond. Please feel free to comment on this issue if  you concerns remain. Happy to re-open and continue discussion.
