### ISSUE TITLE
display warning message when a query you've performed has returned more results than the limit

### ISSUE THREAD

**Issue by jhpoelen** [ropensci/rglobi#44]
for context see https://github.com/globalbioticinteractions/globalbioticinteractions/issues/799 .

suggested by @H-Waters .

**Comment by H-Waters** [comment]
Thanks for opening this!

Perhaps something along the lines of: "Warning: Results limit has been reached. Query has generated more results than can be returned via the Web API. Use pagination to retrieve all results."?

**Comment by jhpoelen** [comment]
I much like your proposed text. Would you feel comfortable adding the functionality to the rglobi package and prepare a pull request? It might take me a while to add this important feature. Naturally, you'd get author credits. I'd be happy to help review and release a new version of rglobi.

**Comment by H-Waters** [comment]
I haven't edited package code before, but I think I can do it/work out how to do it. I've had a look in the rglobi.R code and it looks like it would be simple enough to add it in. Might take me a couple of days to find the time to do it!

Is the limit on the number of results returned always 1024 rows? Is that something I'm safe assuming? e.g. for making an edited requesturl based on `otherkeys = list("limit"=1, "skip"=1024)`

**Comment by jhpoelen** [comment]
@H-Waters thanks for offering to take a stab at implementing your desired functionality. Looking forward to what you may come up with.

And, the limit is configurable as documented in the rglobi vignettes and documentation.

If not explicit set, I believe the limit defaults to 1024. 

Please let me know if you have any more questions / comments / ideas . . .
