### ISSUE TITLE
Citations are not coming with rglobi

### ISSUE THREAD

**Issue by SagarAdhurya** [ropensci/rglobi#46]
Citations are not appearing with get_interactions function

**Comment by jhpoelen** [comment]
@SagarAdhurya thanks for your message . To get citations with get_interactions, see #38 or related section "Find citations using individual interaction records" in the globi vignette at https://cran.r-project.org/web/packages/rglobi/vignettes/rglobi_vignette.html . 

Please confirm that these reference address your issue.

**Comment by SagarAdhurya** [comment]
Thanks, it worked

**Comment by jhpoelen** [comment]
@SagarAdhurya glad to hear and thanks for confirming.
