### ISSUE TITLE
Problem with pagination

### ISSUE THREAD

**Issue by SagarAdhurya** [ropensci/rglobi#47]
I am trying to use pagination as directed in Vignettes. But whatever configuration I am using, it is returning the same data and same warning. My code is:
otherkeys = list("limit"=1000, "skip"=0)
first_page <- get_interactions_by_taxa(sourcetaxon = "Chironomidae", interactiontype =  c("preysOn", "eats"))[,c(2,3,5,7,8)]
otherkeys = list("limit"=1000, "skip"=1000)
second_page <- get_interactions("Chironomidae", c("preysOn", "eats"))[,c(2,3,5,7,8)]
otherkeys = list("limit"=1000, "skip"=2000)
third_page <- get_interactions("Chironomidae", c("preysOn", "eats"))[,c(2,3,5,7,8)]
otherkeys = list("limit"=1000, "skip"=3000)
Fourth_page <- get_interactions("Chironomidae", c("preysOn", "eats"))[,c(2,3,5,7,8)]

**Comment by jhpoelen** [comment]
When after installing rglobi using

```R 
install.packages('rglobi')
```

I ran 
```R
results_page1  <- rglobi::get_interactions_by_taxa(sourcetaxon = "Chironomidae", interactiontype = c("preysOn", "eats"), otherkeys = list("limit"=1000, "skip"=0))[,c(2,5,7)]
head(results_page1)
```

to produce:

```R
     source_taxon_name interaction_type               target_taxon_name       
1 Macropelopia adaucta             eats fine particulate organic matter
2 Macropelopia adaucta             eats        other microinvertebrates
3 Macropelopia adaucta             eats                  Amphora libyca
4 Macropelopia adaucta             eats              Navicula clementis
5 Macropelopia adaucta             eats              Navicula phyllepta
6 Macropelopia adaucta             eats                 Navicula cincta
Warning message:
In rglobi::get_interactions_by_taxa(sourcetaxon = "Chironomidae",  :
  Default results limit reached. Consider increasing limit parameter and/or using pagination to retrieve all results. See rglobi vignette section on pagination for help modifying limit/skip parameters.
```

with 
```R
> dim(results_page1)
[1] 1000    3   
```

Then, requesting the next page:

```R
results_page2  <- rglobi::get_interactions_by_taxa(sourcetaxon = "Chironomidae", interactiontype = c("preysOn", "eats"), otherkeys = list("limit"=1000, "skip"=1000))[,c(2,5,7)]
head(results_page2)
```

produces:

```R
           source_taxon_name interaction_type            target_taxon_name
1 Synorthocladius semivirens             eats          Cocconeis pediculus
2 Synorthocladius semivirens             eats        Tabularia fasciculata
3 Synorthocladius semivirens             eats           Cocconeis disculus
4 Synorthocladius semivirens             eats Navicula cuspidata halophila
5 Synorthocladius semivirens             eats          Nitzschia frustulum
6 Synorthocladius semivirens             eats         Gomphonema olivaceum
```

with 

```R
> dim(results_page2)
[1] 1000    3
```

@SagarAdhurya note that the start (or head) of the first page appears to be different than the start of the second page. So, as far as I can tell, the pagination is working as designed. 

Can you please reproduce these result?

**Comment by SagarAdhurya** [comment]
sorry, I missed the part, `otherkeys=otherkeys`
It works well now
Sorry for the mistake from my end

**Comment by jhpoelen** [comment]
Glad to hear your got it working now! Thanks for sharing your notes.
