### ISSUE TITLE
Issue with get_interactions_by_taxa

### ISSUE THREAD

**Issue by SagarAdhurya** [ropensci/rglobi#48]
In get_interactions_by_taxa, interactiontype is not working. My command is:
> first_page <- get_interactions_by_taxa(sourcetaxon = "Leptophlebiidae", interactiontype="preysOn",  returnobservations= T, read_csv = "verbatim-interactions.csv")
Rows: 40 Columns: 4                                         
── Column specification ──────────────────────────────────────
Delimiter: ","
chr (4): interaction, source, target, termIRI

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Error in get_interactions_by_taxa(sourcetaxon = "Leptophlebiidae", interactiontype = "preysOn",  : 
  Unsupported interaction type(s)

**Comment by jhpoelen** [comment]
@SagarAdhurya thanks for your message!

Using 

```R
?rglobi::get_interactions_by_taxa
```

I found the following description of read_csv - 

```
read_csv: function used to find csv associated to query url, defaulting
          to online query method
```

however, from your example, it appears that you are assigning a string (i.e., ```verbatim-interactions.csv```), not a function. 


You'll find the default read_csv function at:

https://github.com/ropensci/rglobi/blob/6ea94cb8369b263840226b12d27480c8dcdcd811/R/rglobi.R#L40-L53

Please confirm that you can access the instructions on how to use the read_csv argument and that you were able to find the default implementation of the function. 

I do like your idea to swap out the read_csv function with a locally available data file: having to rely on online resources makes reproducing results tricky sometimes.

**Comment by jhpoelen** [comment]
Happy to hear you got it, and please don't hesitate to share ideas, questions or notes again.
